RECOVREE/recovree-app

client/scripts/controllers/homeController.js
client/scripts/controllers/reflectionFormController.js
client/scripts/factories/UserService.js
client/styles/style.css
client/views/index.html
client/views/partials/header.html
client/views/templates/home.html
client/views/templates/reflectionForm/reflect1.html
client/views/templates/reflectionForm/reflect10.html
client/views/templates/reflectionForm/reflect11.html
client/views/templates/reflectionForm/reflect12.html
client/views/templates/reflectionForm/reflect4.html
client/views/templates/reflectionForm/reflect5.html
client/views/templates/reflectionForm/reflect6.html
client/views/templates/reflectionForm/reflect7.html
client/views/templates/reflectionForm/reflect8.html
client/views/templates/reflectionForm/reflect9.html

Completes daily Reflection Form, adds some styling, begins building sessionObject

Feature daily form

---

client/scripts/factories/UserService.js

feelings chart displays top 5 feelings from all reflection forms

Top 5 Feelings

---

client/views/templates/dayDetail.html
client/views/templates/home.html
client/views/templates/reflectionForm/reflect1.html
client/views/templates/reflectionForm/reflect2.html
client/views/templates/reflectionForm/reflect3.html
client/views/templates/reflectionForm/reflect4.html
client/views/templates/reflectionForm/reflect5.html
client/views/templates/reflectionForm/reflect6.html
client/views/templates/reflectionForm/reflect7.html
client/views/templates/reflectionForm/reflect8.html

Adds styling and logout button

Feature styling

---

client/scripts/controllers/loginController.js
client/scripts/factories/UserService.js
client/views/templates/register.html

moves user and registration objects out of the login controller and into the user service factory

Feature registration to factory

---

client/views/templates/register.html
server/app.js
server/modules/sessionObject.js
server/routes/reflection.js

I trimmed down the reflections route quite a bit.  I tested reflections and csv export and everything should be working.  The streak count inconsistency should be fixed now too.

Feature authentication

---

client/scripts/controllers/homeController.js
client/scripts/controllers/loginController.js
client/scripts/factories/UserService.js
client/styles/style.css
client/views/partials/header.html
client/views/partials/nav.html
client/views/templates/login.html
client/views/templates/reflectionForm/reflect1.html
client/views/templates/reflectionForm/reflect10.html
client/views/templates/reflectionForm/reflect2.html
client/views/templates/reflectionForm/reflect4.html
client/views/templates/reflectionForm/reflect6.html
client/views/templates/reflectionForm/reflect7.html
client/views/templates/reflectionForm/reflect9.html

resolves iphone 5 errors. Still has some reflection form inconsistancy.

Feature previous button

---

client/scripts/controllers/homeController.js
client/scripts/controllers/navController.js
client/views/partials/blankNav.html
client/views/partials/header.html
client/views/partials/nav.html
client/views/templates/reflectionForm/reflect1.html
client/views/templates/reflectionForm/reflect2.html

Feature form styling kbt

---

client/scripts/factories/UserService.js
client/views/templates/dayDetail.html
client/views/templates/reflectionForm/reflect1.html
server/models/reflection.js
server/routes/reflection.js

Added overall feeling to the reflection form, reflection object/schema, and the daily view. 
Also, minor changes on the UserService factory, just made scaled values 1 instead of 0.

Feature overallsummary

---

client/styles/style.css
client/views/templates/dayDetail.html
client/views/templates/home.html

Removed chart centered streak number and instead put value before graph, and streak goal below graph. Also, some font styling and size changes for the home view.

Feature streakgraph

---

client/views/templates/home.html

Changes home screen HTML so that it will be scrollable if the screen is too smal to display everything.

Feature data build kbt

---

Gruntfile.js
client/scripts/clientapp.js
client/scripts/controllers/GraphsController.js
client/scripts/controllers/adminExportController.js
client/scripts/controllers/navController.js
client/scripts/factories/AdminService.js
client/scripts/factories/UserService.js
client/views/partials/header.html
client/views/templates/Weeklygraphs.html
server/modules/csvExport.js
server/routes/reflection.js
server/routes/user.js

There's a bunch of stuff here so if you get to Prime before me, I can go over all of this with whoever is peeping this.
--vv
I started with the authentication - isAuthenticated wasn't catching users that weren't logged in because it needed to be a function call.  I corrected it throughout the backend.
I also noticed that the logout function called when you click the button in the header dropdown wasn't actually calling the logout function in the backend - it was just clearing the userObject.  I added the call to the UserService logout function but just realized I didn't do the same in AdminService.  I'll change this tomorrow (we just need to copy and paste the function in the UserService into the AdminService).
--These two things take care of the memberID undefined error that was popping …

Feature weekly

---

client/scripts/controllers/loginController.js
client/scripts/factories/UserService.js
client/styles/style.css
client/views/templates/login.html
client/views/templates/register.html

Adds popup when user registers.

Feature user feedback kbt

---

client/scripts/controllers/navController.js
client/scripts/factories/UserService.js
client/views/partials/header.html
client/views/templates/Weeklygraphs.html
client/views/templates/adminExport.html
client/views/templates/login.html
client/views/templates/reflectionForm/reflect1.html
client/views/templates/reflectionForm/reflect10.html
client/views/templates/reflectionForm/reflect12.html
client/views/templates/reflectionForm/reflect4.html
client/views/templates/reflectionForm/reflect6.html
client/views/templates/reflectionForm/reflect9.html
client/views/templates/register.html
client/views/templates/resources.html

dropdown in reflection form becomes a slider, confirm on logout on admin side, logout on admin does not show dropdown menu, text size changes, and button color changes

added in minor style changes and whatnot

---

client/scripts/controllers/adminExportController.js
client/scripts/controllers/dayDetailController.js
client/scripts/controllers/homeController.js
client/scripts/factories/AdminService.js
client/views/templates/dayDetail.html
client/views/templates/home.html

Added quotes when didn't complete reflection

Feature streak

---

client/styles/style.css
client/views/templates/resources.html
client/views/templates/termsOfUse.html

Adds in terms of use view with styling.
Resources links now open in a new window.

Feature minorstyle

---

client/views/templates/dayDetail.html

This should be just the daily view select.  Defaults to today - yesterdays goal isn't included unless the current day is selected because it seemed redundant.

Feature day view

---

server/modules/convertCount.js
server/modules/csvExport.js
server/modules/sessionObject.js
server/modules/twilio.js
server/routes/reflection.js
server/routes/register.js

Cleaned up a bunch of comments and console logs in the backend.

Feature comment cleanup

---

client/scripts/clientapp.js
client/scripts/controllers/navController.js
client/views/partials/header.html
client/views/templates/contactUs.html

Feature contact us kbt

---

client/scripts/clientapp.js
client/scripts/controllers/adminExportController.js
client/scripts/controllers/navController.js
client/scripts/factories/AdminService.js
client/views/partials/header.html
client/views/templates/contactUs.html

Changes structure of adminexport controller, adds getAdminObject function, then sorts adminObject by date so that graph appears in the correct date order.

Feature admin graph kbt

---

.gitignore
client/scripts/controllers/loginController.js
client/scripts/factories/UserService.js
server/app.js
server/modules/twilio.js
server/routes/user.js

Uses node modules to export sendSMS function. Password reset link will be sent via text message. Created BASE_URL .env variable for production purposes.

Password reset

---

client/scripts/factories/UserService.js

Changes post/put logic for reflection form.

Feature prev next kbt

---

client/scripts/controllers/dayDetailController.js
client/scripts/controllers/loginController.js
client/scripts/factories/UserService.js
client/views/templates/dayDetail.html

cleans up a bunch of console logs.
adds currentDailyReflection to the UserService. This resolves the issue with dailyDetail being empty when the user first navigates to that view.

Daily detail troubleshoot kbt

---

client/views/templates/reflectionForm/reflect6.html

Melissa requested a couple of wording changes on these questions.

changes wording for two questions on reflect6.html
